version: "3"
services:
  aigc-server:
    image: dudulu/aigc-server:v0.0.0-beta05
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    command:
      - aigc-server
      - start
    volumes:
      - storage:/usr/local/aigc-server/storage
    network_mode: host
  fschat-controller:
    image: dudulu/fschat:v0.2.36
    restart: always
    ports:
      - "21001:21001"
    command:
      - python3
      - -m
      - fastchat.serve.controller
      - --host
      - '0.0.0.0'
      - --port
      - '21001'
    network_mode: host