hostfile=""
deepspeed --hostfile=$hostfile fine-tune.py  \
    --report_to "none" \
    --data_path "/data/train-data/train-4k.jsonl" \
    --model_name_or_path "/data/base-model/baichuan2-7b-base" \
    --output_dir "/data/ft-model/ft-baichuan2-7b-base-1-1udh-4k" \
    --model_max_length 2048 \
    --num_train_epochs 4 \
    --per_device_train_batch_size 24 \
    --gradient_accumulation_steps 1 \
    --save_strategy 'epoch' \
    --evaluation_strategy 'epoch' \
    --learning_rate 2e-5 \
    --lr_scheduler_type constant \
    --adam_beta1 0.9 \
    --adam_beta2 0.98 \
    --adam_epsilon 1e-8 \
    --max_grad_norm 1.0 \
    --weight_decay 1e-4 \
    --warmup_ratio 0.0 \
    --logging_steps 1 \
    --gradient_checkpointing True \
    --deepspeed ds_config.json \
    --bf16 True \
    --tf32 True